config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  root to: "pages#home"
  get '/privacy', to: 'pages#privacy'
  get '/settings', to: 'pages#settings'
  resources :users, only: %i[index show] do
    resource :profile, except: %i[destroy show]
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  resources :posts, except: [:show, :edit, :update]
  resources :comments, except: [:show, :edit, :update, :index]
  resources :likes, only: [:create, :destroy]
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :only_current_user
  
  def new
    @profile = Profile.new
  end

  def create
    @user = User.find(params[:user_id])
    @profile = @user.build_profile(profile_params)

    if @profile.save
      flash[:success] = "Profile picture updated!"
      redirect_to root_path
    else
      flash[:danger] = "Something went wrong!"
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @profile = @user.profile
  end

  def update
    @user = User.find(params[:user_id])
    @profile = @user.profile
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile updated!"
      redirect_to root_path
    else
      render action: :edit
    end
  end


  private

  def profile_params
    params.require(:profile).permit(:avatar)
  end
end

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path do |f| %>
  <div class="field mb-3">
    <%= f.label :avatar, "Profile Picture", class: "form-label" %>
    <%= f.file_field :avatar, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= f.submit "Update Profile", class: "btn btn-primary" %>
  <div>
<% end %>

app/views/profiles/_profile_sidebar.html.erb
<% if user.profile.nil? || !user.profile.avatar.attached? %>
  <%= image_tag("default/default-profile.png", size: "150x150") %><br>
  <% if current_user == user %>
    <%= link_to "Upload profile picture", new_user_profile_path(user_id: user.id) %>
  <% end %>
<% else user.profile.avatar.attached? %>
  <%= image_tag(url_for(user.profile.avatar), size: "150x150") %>
<% end %>

<h3 class="mt-3"><%= link_to user.full_name, user, class: "user_sidebar_anchor" %></h3>

<% unless current_user.id == user.id || is_friend?(user.id) %>
  <%= link_to "Add Friend", user_friendships_path(user_id: @user.id), method: :post, class: 'btn btn-primary' %>
<% end %>

<h5 class="mt-5">These are your Friends</h5>
<% friends.each do |friend| %>
  <div class="mt-3 d-flex flex-row justify-content-start align-items-center">
    <% if friend.profile.nil? || !friend.profile.avatar.attached? %>
      <%= image_tag("default/default-profile.png", size: "50x50", class: "rounded-circle me-3 ms-3")%>
    <% else %>
      <%= image_tag(url_for(friend.profile.avatar), size: "50x50", class: "rounded-circle me-3 ms-3") %>
    <% end %>
    <%= link_to friend.full_name, friend, class: "user_sidebar_anchor" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container-fluid">
  <div class="row justify-content-md-center">
    <div class="col-md-4">
      <div class="card card-body bg-light">
        <h1 class="text-center">Update your profile picture</h1>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container-fluid">
  <div class="row justify-content-md-center">
    <div class="col-md-4">
      <div class="card card-body bg-light">
        <h1 class="text-center">Update your profile pciture</h1>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>