config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  root to: "pages#home"
  get '/privacy', to: 'pages#privacy'
  get '/settings', to: 'pages#settings'
  resources :users, only: %i[index show] do
    resource :profile, except: %i[destroy show]
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  resources :posts, except: [:show, :edit, :update]
  resources :comments, except: [:show, :edit, :update, :index]
  resources :likes, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook]

  has_one :profile

  has_many :posts, dependent: :destroy
  has_many :friend_posts, through: :friends, source: :posts

  has_many :comments, dependent: :destroy

  has_many :notifications, foreign_key: 'recipient_id'
  
  has_many :likes, dependent: :destroy

  has_many :friend_sent, class_name: 'Friendship', foreign_key: 'sent_by_id', inverse_of: 'sent_by', dependent: :destroy
  has_many :friend_request, class_name: 'Friendship', foreign_key: 'sent_to_id', inverse_of: 'sent_to', dependent: :destroy
  has_many :friends, -> { merge(Friendship.friends) }, through: :friend_sent, source: :sent_to
  has_many :pending_requests, -> { merge(Friendship.not_friends) }, through: :friend_sent, source: :sent_to
  has_many :recieved_requests, -> { merge(Friendship.not_friends) }, through: :friend_request, source: :sent_by

  # Returns an array of posts from most recent to oldest by the user and user's friends
  def friend_and_user_posts
    user_friends = friends
    all_posts = []
    user_friends.each do |friend|
      friend.posts.each do |post|
        all_posts << post
      end
    end
    posts.each do |post|
      all_posts << post
    end
    ordered_posts = all_posts.sort_by { |post| post[:created_at] }.reverse
  end

  def full_name
    first_name + " " + last_name
  end

  def self.from_omniauth(auth)
    name_split = auth.info.name.split(" ")
    user = User.where(email: auth.info.email).first
    user ||= User.create!(provider: auth.provider, uid: auth.uid, last_name: name_split[1], first_name: name_split[0], email: auth.info.email, password: Devise.friendly_token[0, 20])
    user
  end
  
  def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["user_hash"]
          user.email = data["email"]
        end
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook

    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def create
    super
    # Disabling welcome emails while waiting to resolve an issue with Mailgun email service
    #UserMailer.welcome_email(resource).deliver unless resource.invalid?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @friends = @user.friends

    if current_user.id == @user.id
      @new_post = @user.posts.build
    end
  end
end

app/views/users/_notification_sidebar.html.erb
<h3>Notifications</h3>
<h5>Friend Requests</h5>
<% current_user.recieved_requests.each do |request| %>
  <%= link_to request.full_name, request %>
  <%= link_to 'Accept', accept_friend_user_friendships_path(user_id: request), class: 'btn btn-success' %>
  <%= link_to 'Decline', decline_friend_user_friendships_path(user_id: request), class: 'btn btn-danger' %>
<% end %>

app/views/users/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2 text-center">
      <%= render partial: "profiles/profile_sidebar", locals: { user: current_user, friends: current_user.friends } %>
    </div>
    <div class="col-md-8 ps-5 pe-5">
      <h3>People!</h3>
      <% @users.each do |user| %>
        <% next if user == current_user %>

        <div class="d-flex flex-row align-items-center card mb-4 pt-3 pb-3 ps-2 ">
          <% if profile_image?(user) %>
            <%= image_tag("default/default-profile.png", size: "75x75", class: "rounded-circle me-3 ms-3")%>
          <% else %>
            <%= image_tag(url_for(user.profile.avatar), size: "75x75", class: "rounded-circle me-3 ms-3") %>
          <% end %>
          <h5 class="w-75"><%= user.full_name %></h5>
          <% if is_friend?(user.id) %>
            <h5>Your Friend</h5>
          <% elsif current_user.pending_requests.where("sent_to_id = ?", user.id).exists? %>
            <span class="btn btn-secondary">Pending Friend</span>
          <% elsif waiting_for_response(user) %>
            <%= link_to 'Accept', accept_friend_user_friendships_path(user_id: user.id), class: 'btn btn-success m-1' %>
            <%= link_to 'Decline', decline_friend_user_friendships_path(user_id: user.id), class: 'btn btn-danger' %>
          <% else %>
            <%= link_to 'Add Friend', user_friendships_path(user_id: user.id), method: :post, class: 'btn btn-primary' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2 text-center">
      <%= render partial: "profiles/profile_sidebar", locals: { user: @user, friends: @friends } %>
    </div>
    <div class="col-md-8 ps-5 pe-5">
      <h3>NEWS FEED</h3>
      <% if current_user.id == @user.id %>
        <%= render partial: "posts/form", object: @new_post, as: :post %>
      <% end %>
      <%= render partial: "posts/news_feed", object: @user.posts, as: :posts %>
    </div>
    <div class="col-md-2">
      <% if current_user == @user %>
        <%= render partial: "notification_sidebar" %>
      <% else %>
        Ads
      <% end %>
    </div>
  </div>
</div>