config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  root to: "pages#home"
  get '/privacy', to: 'pages#privacy'
  get '/settings', to: 'pages#settings'
  resources :users, only: %i[index show] do
    resource :profile, except: %i[destroy show]
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  resources :posts, except: [:show, :edit, :update]
  resources :comments, except: [:show, :edit, :update, :index]
  resources :likes, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  
  # GET /posts or /posts.json
  def index
    @user = User.find(current_user.id)
    @posts = @user.friend_and_user_posts
    @new_post = @user.posts.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_back fallback_location: root_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-1">
    <%= form.text_area :content, placeholder: "What's on your mind?", class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_news_feed.html.erb
<% posts.each do |post| %>
  <% next if post.id.nil? %>
  <div class="card mb-3 ps-2 pe-2">
    <p class="mt-1 mb-0 post-text"><b><%= post.user.full_name %></b></p>
    <span class="post-date-text"><%= post.created_at.strftime("%D") %></span>
    <p class=" mt-2 post-text"><%= post.content %></p>
    <span class="post-text"><i class="fa fa-thumbs-o-up"> <%= post.likes.count %></i></span>
    <span class="pt-2 pb-2 like-comment-wrapper">
      <div class="row m-0">
        <% if has_been_liked?(post) %>
          <%= link_to "UnLike", like_path(id: find_like(post).id, post_id: post.id, user_id: current_user.id), method: :delete, class: "col-md-6 rounded" %>
        <% else %>
          <%= link_to "Like", likes_path(post_id: post.id), method: :post, class: "col-md-6 rounded" %>
        <% end %>
        <%= link_to 'Comment', new_comment_path(post_id: post.id, user_id: current_user.id), class: "col-md-6 rounded" %>
      </div>
    </span>
    <div class="comment-wrapper d-flex flex-column align-items-start">
      <% post.comments.each do |comment| %>
        <div class="card mb-2 p-2">
          <p class="post-text"><b><%= comment.user.full_name %></b></p>
          <p class="post-text mb-0"><%= comment.comment %></p>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2 text-center">
      <%= render partial: "profiles/profile_sidebar", locals: { user: @user, friends: @user.friends } %>
    </div>
    <div class="col-md-8 ps-5 pe-5">
      <h3>NEWS FEED</h3>
      <%= render partial: "form", object: @new_post, as: :post %>
      <%= render partial: "news_feed", object: @posts, as: :posts%>
    </div>
    <div class="col-md-2">
      <%= render partial: "users/notification_sidebar" %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>